<?php

 namespace Drupal\nishaj_exercise\Plugin\Block;    # namespace where the block plugin class is located.
 use Drupal\Core\Block\BlockBase;     # imports the BlockBase class.
 use Drupal\Core\Form\FormStateInterface;   # imports the FormStateInterface class.

/**
  * Provides simple block for d4drupal.
  * @Block (
  * id = "nishaj_exercise",
  * admin_label = "Custom Plugin Block"
  * )
  */

class CustomBlock extends BlockBase{   # custom block class defined extends the BlockBase class.
    /**
     * {@inheritdoc}
     */

    public function build() {   #  returns the rendered form generated by the CustomForm form class defined in the same module.
        $form =\Drupal::formBuilder()->getForm('\Drupal\nishaj_exercise\Form\CustomForm');   # formBuilder() service is used to get the form object and then calling the getForm() method with the fully-qualified name of the CustomForm form class to build the form.
        return $form;    # return function.
    }
}
